layout_spectrum: 0.3650963
typography_spectrum: 0.4044243
color:
  saturation: 0.02294894
  lightness: 0.04009482
  brandStrength: 0.5113662
  rhythmicContrast: 0.3107302
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
name: George R. Kasica
